routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['middleware' => 'auth'], function(){
	Route::resource('reset', 'ResetController');
	Route::resource('print', 'PrintController');
	Route::get('get-inventory', 'ItemlistController@getInventoryList')->name('get-inventory');
	Route::post('get-product-list', 'ItemlistController@getProductList');
	Route::post('/search', 'ItemlistController@search');
	Route::resource('itemlist', 'ItemlistController');
	Route::resource('store', 'StoreController');
	Route::resource('user', 'RegistrationController');
	Route::get('get-json-order/{order}', 'OrderProductController@getJsonOrder')->name('get-json-order');
	Route::resource('order', 'OrderController');
	Route::resource('orderproduct', 'OrderProductController');
	Route::resource('inventory', 'ItemMetaController');
	Route::resource('pos', 'SaleController');
	Route::resource('invoice', 'CustomerController');

	Route::put('return', [
        'as' => 'return.approved',
        'uses' => 'ReturnItemController@approved'
    ]);

	Route::put('pull-outs', [
        'as' => 'pull-outs.approved',
        'uses' => 'PullOutController@approved'
    ]);
	
	Route::get('pull-outs/export/{id}', [
        'as' => 'pull-outs.export',
        'uses' => 'ExcelExportController@exportPullOut'
    ]);


	Route::resource('return', 'ReturnItemController');
	Route::resource('pull-outs', 'PullOutController');
	Route::resource('outstock', 'OutStockController');
	Route::resource('bonus', 'BonusController');
	Route::get('/get-json/{id}', 'BonusController@getJson')->name('get-json');
	Route::get('/get-sales/{id}', 'BonusController@getSalesDetails'); // test
	Route::resource('export', 'ExportController');
	Route::resource('expenses', 'ExpensesController');

	Route::resource('transactions', 'SystemLogController');

	Route::resource('inventories', 'InventoryLogsController');

	Route::post('/import', 'ImportController@import');

	
	Route::post('/export-daily-sales', 'ExcelExportController@export');
	Route::post('/export-daily-expenses', 'ExcelExportController@exportExpense');

	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::get('/home', 'HomeController@index')->name('dashboard');
	Route::get('/dashboard/{store}', 'HomeController@index')->name('dashboard');
});

Auth::routes();
//Route::get('/', 'HomeController@index')->name('dashboard');

resources/views/bonus.blade.php
@if(auth::check())
  @unless (Auth::user()->store_id===1 || Auth::user()->type===1)
    <script>window.location = "dashboard";</script>
  @endunless
@endif


@extends('layouts.master-layout')

@section('content')
 
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Bonus</li>
       
      </ol>
            
        <div class="card">
            <a href="{{url('/print').'/'.$storeId}}" class="btn btn-primary"><i class="fa fa-print"></i> Print</a>
        </div>
        <hr>
         <!-- Example DataTables Card-->
         <div class="card-header">
            <div class="row">
              <div class="col-sm-2">
                <i class="fa fa-table"></i> Today's Sales
            </div>
            <div class="col-sm-5">
              <form action="{{ url('export-daily-expenses') }}" method="POST">
                @csrf
                @method('POST')
                <input type="hidden" name="store_id" value="{{ $storeId }}" class="storeId">
                <div class="row"><div class="col-sm-7">
                  <input type="date" name="filter_date" required="required" class="form-control">
                </div>
                  <div class="col-sm-5"><button type="submit" class="form-control btn btn-danger">Export Expenses</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="col-sm-5">
              <form action="{{ url('export-daily-sales') }}" method="POST">
                @csrf
                @method('POST')
                <input type="hidden" name="store_id" value="{{ $storeId }}" class="storeId">
                <div class="row"><div class="col-sm-7">
                  <input type="date" name="filter_date" required="required" class="form-control">
                </div>
                  <div class="col-sm-5"><button type="submit" class="form-control btn btn-success">Export Daily Sales</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="table-responsive">

            <table class="table table-hover" id="dailysales" class="display" style="width:100%">
                  <thead>
                    <tr>
                      <th scope="col">Total&nbsp;Bonus</th>
                      <th>Barcode</th>
                      <th>Item Description</th>
                      <th>Price</th>
                      <th>Qty</th>
                      <th>Total</th>
                      <th>OS#</th>
                      <th>OR#</th>
                      <th>Transaction Time</th>
                    </tr>
                  </thead>
                  <tbody>                  
                  </tbody>
                </table>
          </div>
        </div>
        <div class="card-footer small text-muted"></div>
      </div>
    </div>
    </div>
@endsection
@push('script')
 <script type="text/javascript">
      $(document).ready(function() {
        $('#dailysales').DataTable( {
                  ajax: window.location.origin+'/get-json/'+$('.storeId').val(),
                  columns: [
                      { data: 'bonus'},
                      { data: 'barcode'},
                      { data: 'description'},
                      { data: 'price'},
                      { data: 'qty'},
                      
                      { data: 'grandtotal'},
                      { data: 'OS#'},
                      { data: 'OR#'},
                      { data: 'created_at', render: function (data, type, row) {
                          return type === 'export' ?
                              data.replace( /[$,]/g, '' ) :
                              data;
                      } }
                  ],
                  dom: 'Bfrtip',
                  buttons: [
                      // {
                      //     extend: 'excelHtml5',
                      //     title: 'Daily Sales Report',
                      //     message: '',
                      //     exportOptions: { orthogonal: 'export' }
                      // },
                      // {
                      //     extend: 'pdfHtml5',
                      //      title: 'Daily Sales Report',
                      //      message: '',
                      //     exportOptions: { orthogonal: 'export' }
                      // }
                  ]
              } );
    });
  </script>
@endpush 

resources/views/check-stocks.blade.php
@if(auth::check())
  @unless (Auth::user()->store_id===1 || Auth::user()->type===1|| Auth::user()->type===2)
    <script>window.location = "dashboard";</script>
  @endunless
@endif


@extends('layouts.master-layout')


@section('content')
    
        <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Filter By Barcode</li>
      </ol>
        @if(session('error'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{session('error')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
        @endif


      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
           <i class="fa fa-table"></i> Filter By Barcode
           <br>
           <br>
            <form action="{{ route('inventories.store') }}" method="post">
                @csrf
                @method('POST')
                <div class="row">
                    <div class="col-sm-3">
                        <input type="text" class="form-control" name="barcode">
                    </div>
                    
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary form-control">Filter</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-sm-4">
                   <p> Barcode: 
                       @if (!empty($product))
                        <strong>{{ $product->barcode }}</strong> -  {{ $product->desc}}
                       @endif
                    </p>
                   <br>
                </div>
            </div>
          <div class="table-responsive">
            <table class="table table-bordered" id="inventoryList" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Store</th>
                  <th>QTY</th>
                </tr>
              </thead>
              <tbody>
                @if (!empty($inventories))
                    @foreach($inventories as $item)
                        <tr>
                            <td>
                                {{ $item->store->name }}
                            </td> 
                            <td>
                                {{ $item->qty }}
                            </td> 
                        </tr>
                    @endforeach
                @endif
                
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted"></div>
      </div>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/itemlist.blade.php
@if(auth::check())
  @unless (Auth::user()->store_id===1 || Auth::user()->type===1 || Auth::user()->type===2)
    <script>window.location = "dashboard";</script>
  @endunless
@endif

@extends('layouts.master-layout')


@section('content')
        <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Items</li>
      </ol>
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <form method="post" action="{{ url('search') }}" >
                @csrf
                <div class="input-group mb-3">
                  <input type="text" name="search" class="form-control" placeholder="Barcode.."  required>
                  <div class="input-group-append">
                    <button class="btn btn-outline-secondary" >Search</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>


      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Product list

        
          <button type="button" class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#insertModal">Add new</button>
      </div>

        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="inventoryList" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Barcode</th>
                  <th>Name</th>
                  <th>Details</th>
                  <th>Category</th>
                  <th>Quantity</th>
                  <th>Price</th>
                  <th>Bonus&nbsp;Type</th>
                  <th>Bonus&nbsp;Amount</th>
                  <th>Action</th>                  
                </tr>
              </thead>
              <tbody>
                @foreach($itemlist as $item)
                    <tr>
                        <td>{{$item['id']}}</td>
                        <td>{{$item['barcode']}}</td>
                        <td>{{$item['name']}}</td>
                        <td>{{$item['desc']}}</td>
                        <td>{{$item['category']}}</td>
                        <td>{{$item['qty']}}</td>
                        <td>{{$item['price']}}</td> 

                        @if($item['bonus_type']===1)
                          <td>Pin Money</td>
                          <td>{{ $item['bonus_amount'] }}</td>
                        @elseif($item['bonus_type']===2)
                          <td>Equipment</td>
                          <td>{{ $item['bonus_amount'] }}</td>
                        @else
                          <td>None</td>
                          <td>None</td>
                        @endif
                        
                                                             
                        <td>
                          @if (Auth::user()->store_id === 1 && Auth::user()->type === 1)
                            <a href="{{ route('itemlist.show' , $item['id'])}}" class="btn btn-warning btn-sm text-white">Update</a>
                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{$item['id']}}">Delete</button>
                          @endif
                            
                            <!-- delete -->
                          <div class="modal fade" id="deleteModal{{$item['id']}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                              
                              <form role="form" method="post" action="{{ route('itemlist.destroy' , $item['id'])}}">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalCenterTitle">Confirm action</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                      @csrf
                                      Are you sure?
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    @method('DELETE')
                                  <button class="btn btn-danger" type="submit">Delete</button>    
                                </div>
                              </form>

                              </div>
                            </div>
                          </div>
                        </td> 
                    </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">
          {{ $itemlist->links()}}
        </div>
      </div>
    </div>

    <table style="display: none;" id="printDelivery">
      <thead>
        <tr>
          <th>Description</th>
          <th>Quantity</th>
          <th>Barcode</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  <!-- Button trigger modal -->  

    <!-- Insert -->
    <div class="modal fade" id="insertModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        
        <form role="form" method="post" action="{{url('itemlist')}}">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Create New Product</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">             
                @csrf
                <label></label>
                <input class="form-control" placeholder="Barcode" name="barcode" type="text" required="required">
                <label></label>
                <input class="form-control" placeholder="Name" name="name" type="text" required="required">
                <label></label>
                <input class="form-control" placeholder="description" name="desc" type="text" required="required">
                <label></label>
                <input class="form-control" placeholder="category" name="category" type="text" required="required">
                <label></label>
                <input class="form-control" placeholder="Initial qty" name="qty" type="number" required="required">
                <label></label>
                <input class="form-control" placeholder="price" name="price" type="number" step=".01" required="required">
                <hr>
                <label class="radio-inline"><input type="radio" name="bonus" value="1"> Pin Money</label>
                <label class="radio-inline"><input type="radio" name="bonus" value="2"> Equipment</label>
                <input class="form-control bonus_amount" placeholder="pin money amount" name="bonus_amount" type="number" id="pin-amount">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <input type="submit" name="submit" class="btn btn-primary">    
          </div>
        </form>

        </div>
      </div>
    </div>
@endsection
@push('script')
 <script type="text/javascript">
      $(document).ready(function() {
        //console.log('test');
        $("input[type=radio]").click(function () {
            if($(this).prop("checked")) { console.log("checked!"); }
            $('input[name="bonus_amount"]').prop('required',true);
        });
          
        // $('#inventoryList').DataTable( {
        //         "processing": true,
        //         "serverSide": true,
        //         "ajax": "get-product-list",
        //         // "deferLoading": 57
        //           // dom: 'Bfrtip',
        //           // buttons: [
        //           //     {
        //           //         extend: 'excelHtml5',
        //           //         title: 'Inventory List',
        //           //         message: '',
        //           //         exportOptions: {  columns: [ 1, 3, 5 ]  }
        //           //     },
        //           //     {
        //           //         extend: 'pdfHtml5',
        //           //          title: 'Inventory List',
        //           //          message: '',
        //           //         exportOptions: {  columns: [ 1, 3, 5 ] }
        //           //     }
        //           // ]
        //       } );
    });
    
  </script>
@endpush 

resources/views/itemlistUpdate.blade.php
@if(auth::check())
  @unless (Auth::user()->store_id===1 || Auth::user()->type===1 || Auth::user()->type===2)
    <script>window.location = "dashboard";</script>
  @endunless
@endif

@extends('layouts.master-layout')


@section('content')
  <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Items</li>
      </ol>
      
      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Product list
          <button type="button" class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#insertModal">Add new</button>
      </div>
        <div class="card-body">
          <form role="form" method="post" action="{{ route('itemlist.update' , $item['id'])}}">
                @csrf
                <label>Barcode</label>
                <input class="form-control" placeholder="Name" name="barcode" type="text" value="{{$item['barcode']}}" required="required">
                 <label>Name</label>
                <input class="form-control" placeholder="description" name="name" type="text" value="{{$item['name']}}" required="required">
                <label>Description</label>
                <input class="form-control" placeholder="description" name="desc" type="text" value="{{$item['desc']}}" required="required">
                <label>Category</label>
                <input class="form-control" placeholder="Category" name="category" type="text" value="{{$item['category']}}" required="required">
                <label>QTY</label>
                <input class="form-control" placeholder="Quantity" name="old_qty" type="number" value="{{$item['qty']}}" readonly>
                <label></label>
                <input class="form-control" placeholder="New Quantity" name="qty" type="number" required="required">
                <label>Price</label>
                <input class="form-control" placeholder="Item Price" name="price" type="number" value="{{$item['price']}}" step=".01" required="required">
                <hr>
                <div class="update-bonus">
                  <label class="radio-inline">
                  <input type="radio" name="bonus" value="1" {{ $item->bonus_type == 1 ? 'checked' : '' }}> 

                  Pin Money</label>
                  <label class="radio-inline"><input type="radio" name="bonus" value="2" {{ $item->bonus_type == 2 ? 'checked' : '' }}  > Equipment</label>

                  <input class="form-control  bonus_amount" placeholder="pin money amount" name="bonus_amount" type="text"  value="{{ $item->bonus_amount != null ? $item['bonus_amount'] : 0 }}" >
                </div>
              @method('PATCH')
              <hr>
              <button class="btn btn-primary" data-dismiss="modal">Submit</button>
          </form>
          </div>
        </div>
      </div>    
@endsection

resources/views/pos2.blade.php
@extends('layouts.master-layout')


@section('content')
    
        <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">POS</li>
      </ol>

        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{session('success')}}
        
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        @endif

        <form role="form" method="post" action="{{url('invoice')}}">                  
                @csrf            
            <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="New sale">    
        </form> 
        <hr>
        <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-money"></i> Point Of Sale  <span class="pull-right"> Total Bonus: <i class="fa fa-"></i> ₱ {{ $total_bonus }}</span> <span class="pull-right" style="margin-right: 20px;">  Grand Total: ₱ {{ $grand_total }} </span>
        </div>
        <div class="card-body">
          <div class="table-responsive"> 
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Total Amount</th>
                  <th>Bonus</th>
                  <th>Date/Time</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach($sales as $sale)
                    <tr>
                        <td> ₱ {{ $sale->total }} </td>
                        <td>₱ {{ $sale->total_bonus }} </td>
                        <td>{{ $sale->created_at }}</td>                 
                        <td><a href="{{ route('pos.show',$sale->id) }}">Details</a></td>
                    </tr>              
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted"></div>
      </div>

@endsection

resources/views/system-logs.blade.php
@if(auth::check())
  @unless (Auth::user()->store_id===1 || Auth::user()->type===1)
    <script>window.location = "dashboard";</script>
  @endunless
@endif


@extends('layouts.master-layout')


@section('content')
    
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Transactions</li>
      </ol>
      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Transaction Logs
          <br>
          <br>

          @if (Auth::user()->store_id === 1)
            <form action="{{ route('transactions.store') }}" method="post">
              @csrf
              @method('POST')
              <div class="row">
                  <div class="col-sm-3">
                    <select name="store_id" id="" class="form-control">
                      <option value=" "disabled selected>Please select store</option>
                      @foreach ($stores as $item)
                          <option value="{{ $item->id }}"
                            @php
                                $storeId = $store->id ?? NULL;
                            @endphp
                            @if(old('store_id',$item->id) == $storeId)
                                selected
                            @endif 
                            >{{ $item->name }}</option>
                      @endforeach
                    </select>
                  </div>
                  
                  <div class="col-sm-2">
                      <button type="submit" class="btn btn-primary form-control">Filter</button>
                  </div>
              </div>
          </form>
          @endif
          
            
        </div>

        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>Store</th>
                      <th>User</th>
                      <th>Log Details</th>
                      <th>Log DateTime</th>
                    </tr>
                  </thead>
              <tbody>
                @if(!empty($logs))
                  @foreach($logs as $item)
                      <tr>
                          <td>{{ $item->store->name }}</td>
                          <td>{{ $item->user->name }}</td>
                          <td>
                              @if (!empty($item->sales))
                                {{ $item }}
                              @else
                                @if (!empty($item->itemlist))
                                  {{ $item }}
                                @else
                                  @if (!empty($item->customer))
                                    {{ $item }}
                                  @else
                                      
                                  @endif
                                @endif
                              @endif

                          </td>
                          <td>
                              {{ $item->created_at }}
                          </td>
                      </tr>   
                    @endforeach
                  @endif
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted"></div>
      </div>
    </div>
@endsection

@push('script')
<script type="text/javascript">
      $(document).ready(function() {
        $('#dataTable').DataTable();
        // $('.export').datepicker();
      });
  </script>

{{-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
<script type="text/javascript">
    $(document).ready(function() {
      $('.export').datepicker();
    });
</script> --}}
@endpush 