routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['middleware' => 'auth'], function(){
	Route::resource('reset', 'ResetController');
	Route::resource('print', 'PrintController');
	Route::get('get-inventory', 'ItemlistController@getInventoryList')->name('get-inventory');
	Route::post('get-product-list', 'ItemlistController@getProductList');
	Route::post('/search', 'ItemlistController@search');
	Route::resource('itemlist', 'ItemlistController');
	Route::resource('store', 'StoreController');
	Route::resource('user', 'RegistrationController');
	Route::get('get-json-order/{order}', 'OrderProductController@getJsonOrder')->name('get-json-order');
	Route::resource('order', 'OrderController');
	Route::resource('orderproduct', 'OrderProductController');
	Route::resource('inventory', 'ItemMetaController');
	Route::resource('pos', 'SaleController');
	Route::resource('invoice', 'CustomerController');

	Route::put('return', [
        'as' => 'return.approved',
        'uses' => 'ReturnItemController@approved'
    ]);

	Route::put('pull-outs', [
        'as' => 'pull-outs.approved',
        'uses' => 'PullOutController@approved'
    ]);
	
	Route::get('pull-outs/export/{id}', [
        'as' => 'pull-outs.export',
        'uses' => 'ExcelExportController@exportPullOut'
    ]);


	Route::resource('return', 'ReturnItemController');
	Route::resource('pull-outs', 'PullOutController');
	Route::resource('outstock', 'OutStockController');
	Route::resource('bonus', 'BonusController');
	Route::get('/get-json/{id}', 'BonusController@getJson')->name('get-json');
	Route::get('/get-sales/{id}', 'BonusController@getSalesDetails'); // test
	Route::resource('export', 'ExportController');
	Route::resource('expenses', 'ExpensesController');

	Route::resource('transactions', 'SystemLogController');

	Route::resource('inventories', 'InventoryLogsController');

	Route::post('/import', 'ImportController@import');

	
	Route::post('/export-daily-sales', 'ExcelExportController@export');
	Route::post('/export-daily-expenses', 'ExcelExportController@exportExpense');

	Route::get('/', 'HomeController@index')->name('dashboard');
	Route::get('/home', 'HomeController@index')->name('dashboard');
	Route::get('/dashboard/{store}', 'HomeController@index')->name('dashboard');
});

Auth::routes();
//Route::get('/', 'HomeController@index')->name('dashboard');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Summitway') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master-layout.blade.php
@if(Auth::check())
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Summitway</title>
  <!-- Bootstrap core CSS-->
  <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">

  <!-- Custom fonts for this template-->
  <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{{asset('vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{{asset('css/sb-admin.css')}}" rel="stylesheet">
  <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>

  <link href="https://printjs-4de6.kxcdn.com/print.min.css" rel="stylesheet">

  
  <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

<style type="text/css">
  #cashFund input{
    width: 65px;
    height: 25px;
    border: none;
  }
  
</style>
  @stack('styles')
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <div id="app">
    @include('layouts.side-nav')
    <div class="content-wrapper">
      <div class="mx-3">
        @include('components.flash')
      </div>
      @yield('content')

      <footer class="sticky-footer">
        <div class="container">
          <div class="text-center">
            <small>Copyright © Summitway 2018</small>
          </div>
        </div>
      </footer>

      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
      </a>

      <!-- Logout Modal-->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>

              <a class="btn btn-primary" href="{{ route('logout') }}"
                  onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
              
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <script src="{{asset('js/app.js')}}"></script>
  <!-- Bootstrap core JavaScript-->
  <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- Core plugin JavaScript-->
  <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>
  <!-- Page level plugin JavaScript-->
  <script src="{{asset('vendor/chart.js/Chart.min.js')}}"></script>
  <script src="{{asset('vendor/datatables/jquery.dataTables.js')}}"></script>
  <script src="{{asset('vendor/datatables/dataTables.bootstrap4.js')}}"></script>
  <!-- Custom scripts for all pages-->
  <script src="{{asset('js/sb-admin.js')}}"></script>
  <!-- Custom scripts for this page-->
  {{-- <script src="{{asset('js/sb-admin-datatables.min.js')}}"></script> --}}
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
  <!-- Page level JavaScript-->


 
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>


<!-- CASH FUND SCRIPT-->
   <script src="{{asset('js/main.js')}}"></script>
  



  <!-- Notification -->
  <script>
    var notificationDropdown = $('#notification-dropdown');
    var newNotificationIndicator = $('#notification-indicator');
    var notificationsItems = $('#notifications-items');
    var userId = "{{ Auth::id() }}";

    notificationDropdown.trigger('click');

    notificationDropdown.on('click', function(){
      newNotificationIndicator.removeClass('d-block');
    });

    Echo.private('orderStatusUpdated.' + userId)
        .listen('OrderStatusUpdated', (data) => { 
        var orderLog = data.orderLog;
        var orderDate = new Date(orderLog.created_at);
        var existingNotificationItems = notificationsItems.html();
        var newNotificationItem = '<a class="dropdown-item" href="/orderproduct/' + orderLog.order_id + '">' + 
                                '<strong>' + orderLog.type.toUpperCase()  + '</strong>' +
                                '<span class="small float-right text-muted">' + orderDate.toLocaleTimeString('en-US', { hour12: true }) + '</span>' + 
                                '<div class="dropdown-message small">' + orderLog.message + '</div>' +
                              '</a>' + 
                              '<div class="dropdown-divider"></div>';

        newNotificationIndicator.addClass('d-block');
        notificationsItems.html(newNotificationItem + existingNotificationItems);
    });
  </script>
</body>
</html>

@else
<script>window.location = "login";</script>
@endif

@stack('script')

resources/views/layouts/side-nav.blade.php
        <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="#">
      @auth
        {{ Auth::user()->name }}
      @endauth
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        
        @if(Auth::user()->type===1)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{url('/')}}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        @endif
        @if(Auth::user()->store_id===1 && Auth::user()->type===1)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('itemlist')}}">
            <i class="fa fa-fw fa-table"></i>
            <span class="nav-link-text">Products</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('transactions.index')}}">
            <i class="fa fa-user-secret"></i>
            <span class="nav-link-text">Transactions Logs</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('inventories.index')}}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Check Stocks</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('pull-outs.index')}}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Pull Outs</span>
          </a>
        </li>
        @endif

        @if(Auth::user()->store_id===1 &&  Auth::user()->type===2)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('itemlist')}}">
            <i class="fa fa-fw fa-table"></i>
            <span class="nav-link-text">Products</span>
          </a>
        </li> 
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('order')}}">
            <i class="fa fa-fw fa-truck"></i>
            <span class="nav-link-text">Delivery</span>
          </a>  
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('store')}}">
            <i class="fa fa-fw fa-building"></i>
            <span class="nav-link-text">Store</span>
          </a>
        </li>  
        @endif

        @if(Auth::user()->store_id===1 && Auth::user()->type===1)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('store')}}">
            <i class="fa fa-fw fa-building"></i>
            <span class="nav-link-text">Store</span>
          </a>
        </li>
        @endif

        @if(Auth::user()->type===1)

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('user')}}">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text">User</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('order')}}">
            <i class="fa fa-fw fa-truck"></i>
            <span class="nav-link-text">Delivery</span>
          </a>  
        </li>
        
        
        @unless(Auth::user()->store_id===1)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('inventory')}}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Inventory</span>
          </a>  
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{url('pos')}}">
            <i class="fa fa-fw fa-calculator"></i>
            <span class="nav-link-text">POS</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{url('return')}}">
            <i class="fa fa-fw fa-share-square"></i>
            <span class="nav-link-text">Return</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ url('bonus', ['store' => Auth::user()->store_id]) }}">
            <i class="fa fa-fw fa-usd"></i>
            <span class="nav-link-text">Bonus</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ url('expenses')}}">
            <i class="fa fa-fw fa-usd"></i>
            <span class="nav-link-text">Expenses</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('transactions.index')}}">
            <i class="fa fa-user-secret"></i>
            <span class="nav-link-text">Transactions Logs</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('pull-outs.index')}}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Pull Outs</span>
          </a>
        </li>
        @endunless
        @endif

        @if(Auth::user()->store_id !=1 && Auth::user()->type===2)
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('inventory')}}">
            <i class="fa fa-fw fa-cubes"></i>
            <span class="nav-link-text">Inventory</span>
          </a>  
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{url('pos')}}">
            <i class="fa fa-fw fa-calculator"></i>
            <span class="nav-link-text">POS</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{url('return')}}">
            <i class="fa fa-fw fa-share-square"></i>
            <span class="nav-link-text">Return</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{url('order')}}">
            <i class="fa fa-fw fa-truck"></i>
            <span class="nav-link-text">Delivery</span>
          </a>  
        </li>
        
        @endif
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item ">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="notification-dropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell"></i>
            <span class="d-lg-none">Notifications
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none" id="notification-indicator">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="notification-dropdown">
            <h6 class="dropdown-header">Notifications:</h6>
            <div class="dropdown-divider"></div>
            <div id="notifications-items"></div>
          </div>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>